<a href="https://colab.research.google.com/github/Dishantchd/1st-sem-project/blob/main/DS_practical_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Practical 1 - Revisiting Pandas and Numpy**





In [ ]:
import pandas as pd
import numpy as np

In [ ]:
import pandas as pd

url = "https://github.com/USERNAME/REPO/raw/main/dataset.xlsx"
df = pd.read_excel(url)

In [ ]:
df.head(5)

,MATHS,SCIENCE,ENGLISH
0,65.0,98.0,91.0
1,95.0,88.0,96.0
2,70.0,80.0,89.0
3,86.0,92.0,74.0
4,65.0,78.0,67.0


In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41 entries, 0 to 40
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   STUDENT ID    40 non-null     object 
 1   STUDENT NAME  34 non-null     object 
 2     GENDER      34 non-null     object 
 3   AGE           34 non-null     float64
 4   STUDENT MAIL  34 non-null     object 
 5   CONTACT NO.   34 non-null     object 
 6   SGPA          34 non-null     float64
 7   ATTENDANCE    34 non-null     float64
 8   MATHS         35 non-null     float64
 9   ENGLISH       34 non-null     float64
 10  SCIENCE       34 non-null     float64
 11  Total_Marks   34 non-null     float64
dtypes: float64(7), object(5)
memory usage: 4.0+ KB


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
df = df[['MATHS', 'SCIENCE', 'ENGLISH']]


In [ ]:
df.dropna()

,MATHS,SCIENCE,ENGLISH
0,65.0,98.0,91.0
1,95.0,88.0,96.0
2,70.0,80.0,89.0
3,86.0,92.0,74.0
4,65.0,78.0,67.0
5,98.0,55.0,51.0
6,96.0,94.0,82.0
7,73.0,79.0,89.0
8,52.0,95.0,92.0
9,53.0,62.0,99.0


In [ ]:
arr = df.to_numpy()

In [ ]:
print("Shape:", arr.shape)
print("Size:", arr.size)
print("Dimensions:", arr.ndim)

Shape: (41, 3)
Size: 123
Dimensions: 2


In [ ]:
df_smallarr = df.iloc[0:5]
df_smallarr

,MATHS,SCIENCE,ENGLISH
0,65.0,98.0,91.0
1,95.0,88.0,96.0
2,70.0,80.0,89.0
3,86.0,92.0,74.0
4,65.0,78.0,67.0


In [ ]:
df_smallarr = df_smallarr.to_numpy()
print(df_smallarr)

[[65. 98. 91.]
 [95. 88. 96.]
 [70. 80. 89.]
 [86. 92. 74.]
 [65. 78. 67.]]


In [ ]:
print("Shape:", df_smallarr.shape)
print("Size:", df_smallarr.size)
print("Dimensions:", df_smallarr.ndim)

Shape: (5, 3)
Size: 15
Dimensions: 2


In [ ]:
df_smallarr.T

array([[65., 95., 70., 86., 65.],
       [98., 88., 80., 92., 78.],
       [91., 96., 89., 74., 67.]])

In [ ]:
df_smallarr * 2


array([[130., 196., 182.],
       [190., 176., 192.],
       [140., 160., 178.],
       [172., 184., 148.],
       [130., 156., 134.]])

In [ ]:
df_smallarr + 5

array([[ 70., 103.,  96.],
       [100.,  93., 101.],
       [ 75.,  85.,  94.],
       [ 91.,  97.,  79.],
       [ 70.,  83.,  72.]])

In [ ]:
df_smallarr - 10

array([[55., 88., 81.],
       [85., 78., 86.],
       [60., 70., 79.],
       [76., 82., 64.],
       [55., 68., 57.]])

In [ ]:
np.dot(df_smallarr.T, df_smallarr)

array([[29771., 33312., 31984.],
       [33312., 38296., 36520.],
       [31984., 36520., 35383.]])

In [ ]:
smallarr_pseudoinv = np.linalg.pinv(df_smallarr)
print(smallarr_pseudoinv)

[[-2.71729800e-02  1.93639736e-02 -6.39589007e-03  1.59518433e-02
   3.87689393e-05]
 [ 2.03062446e-02 -2.80488261e-02 -1.64984831e-02  1.79810986e-02
   1.46654142e-02]
 [ 6.17574934e-03  1.41595059e-02  2.53254600e-02 -3.08869649e-02
  -1.32781537e-02]]
